import AppError from '@shared/errors/AppError';
import FakeUsersRepository from '../repositories/fakes/FakeUsersRepository';
import FakeHashProvider from '../providers/HashProvider/fakes/FakeHashProvider';
import CreateUserService from './CreateUserService';

let fakeHashProvider: FakeHashProvider;
let fakeUsersRepository: FakeUsersRepository;
let createUser: CreateUserService;

describe('CreateUser', () => {
  beforeEach(() => {
    fakeUsersRepository = new FakeUsersRepository();
    fakeHashProvider = new FakeHashProvider();
    createUser = new CreateUserService(fakeUsersRepository, fakeHashProvider);
  });

  it('should be able to create a new user', async () => {
    const user = await createUser.execute({
      username: 'johndoe',
      password: '123456',
      mobile_token: 'example-token',
    });
    expect(user.username).toBe('johndoe');
    expect(user).toHaveProperty('id');
  });

  it('should not be able to create a new user with an existent username', async () => {
    const existentUser = await createUser.execute({
      username: 'johndoe',
      password: '123456',
      mobile_token: 'example-token',
    });
    await expect(
      createUser.execute({
        username: existentUser.username,
        password: 'example',
      })
    ).rejects.toBeInstanceOf(AppError);
  });
});
